import 'dotenv/config';
import express from 'express';import cors from 'cors';import helmet from 'helmet';import bcrypt from 'bcryptjs';import {q} from './db.js';import {sign,requireAuth,requireRole} from './auth.js';
const app=express();app.use(helmet({contentSecurityPolicy:false}));app.use(cors());app.use(express.json({limit:'2mb'}));app.use(express.static('public'));
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Kopun Finance Manager API'}));
app.post('/api/auth/register',asyncRoute(async(req,res)=>{const {companyName,name,username,password}=req.body;if(!companyName||!username||!password||password.length<8)return res.status(400).json({error:'Company, username and password (8+ characters) required'});const client=await (await import('./db.js')).pool.connect();try{await client.query('BEGIN');const b=await client.query('INSERT INTO businesses(name) VALUES($1) RETURNING id,name',[companyName]);const hash=await bcrypt.hash(password,12);const u=await client.query("INSERT INTO users(business_id,name,username,password_hash,role) VALUES($1,$2,$3,$4,'Admin') RETURNING id,business_id,name,username,role",[b.rows[0].id,name||'Administrator',username.toLowerCase(),hash]);await client.query('COMMIT');res.status(201).json({token:sign(u.rows[0]),user:u.rows[0],business:b.rows[0]});}catch(e){await client.query('ROLLBACK');if(e.code==='23505')return res.status(409).json({error:'Username already exists'});throw e;}finally{client.release();}}));
app.post('/api/auth/login',asyncRoute(async(req,res)=>{const {username,password}=req.body;const r=await q('SELECT * FROM users WHERE username=$1 AND active=true',[String(username||'').toLowerCase()]);const u=r.rows[0];if(!u||!await bcrypt.compare(password||'',u.password_hash))return res.status(401).json({error:'Incorrect username or password'});res.json({token:sign(u),user:{id:u.id,business_id:u.business_id,name:u.name,username:u.username,role:u.role}});}));
app.get('/api/me',requireAuth,asyncRoute(async(req,res)=>{const r=await q('SELECT id,name,phone,email,address,default_rate,penalty_rate,grace_days,risk_ratio,alert_days FROM businesses WHERE id=$1',[req.user.businessId]);res.json({user:req.user,business:r.rows[0]});}));
function crud(resource,table,fields){app.get('/api/'+resource,requireAuth,asyncRoute(async(req,res)=>{const r=await q(`SELECT * FROM ${table} WHERE business_id=$1 ORDER BY created_at DESC`,[req.user.businessId]);res.json(r.rows);}));app.post('/api/'+resource,requireAuth,asyncRoute(async(req,res)=>{const allowed=fields.filter(f=>Object.hasOwn(req.body,f));if(!allowed.length)return res.status(400).json({error:'No valid fields'});const vals=allowed.map(f=>req.body[f]);const cols=['business_id',...allowed];const ps=cols.map((_,i)=>'$'+(i+1));const r=await q(`INSERT INTO ${table}(${cols.join(',')}) VALUES(${ps.join(',')}) RETURNING *`,[req.user.businessId,...vals]);res.status(201).json(r.rows[0]);}));}
crud('customers','customers',['customer_code','name','phone','email','reference','dob','occupation','employer','monthly_income','address','notes']);
crud('applications','applications',['application_code','customer_id','application_date','amount','term_months','rate_monthly','monthly_income','monthly_expenses','disposable_income','estimated_installment','debt_income_ratio','risk','guarantor_name','guarantor_phone','security','purpose','notes','status']);
crud('loans','loans',['loan_code','application_id','customer_id','principal','rate_monthly','term_months','interest','total_payable','borrow_date','due_date','frequency','purpose','security','status']);
crud('payments','payments',['receipt_code','loan_id','customer_id','payment_date','amount','method','reference']);
crud('expenses','expenses',['expense_code','expense_date','category','amount','payee','reference','description']);
app.patch('/api/applications/:id/status',requireAuth,requireRole('Admin','Manager','Loan Officer'),asyncRoute(async(req,res)=>{const status=req.body.status;if(!['Pending','Approved','Rejected'].includes(status))return res.status(400).json({error:'Invalid status'});const r=await q('UPDATE applications SET status=$1,reviewed_by=$2,reviewed_at=now() WHERE id=$3 AND business_id=$4 RETURNING *',[status,req.user.id,req.params.id,req.user.businessId]);res.json(r.rows[0]||null);}));
app.put('/api/settings',requireAuth,requireRole('Admin','Manager'),asyncRoute(async(req,res)=>{const x=req.body;const r=await q('UPDATE businesses SET name=COALESCE($1,name),phone=$2,email=$3,address=$4,default_rate=$5,penalty_rate=$6,grace_days=$7,risk_ratio=$8,alert_days=$9,updated_at=now() WHERE id=$10 RETURNING *',[x.name,x.phone||'',x.email||'',x.address||'',x.default_rate??10,x.penalty_rate??2,x.grace_days??3,x.risk_ratio??50,x.alert_days??3,req.user.businessId]);res.json(r.rows[0]);}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error'});});
app.listen(process.env.PORT||3000,()=>console.log('Kopun Finance API running on port '+(process.env.PORT||3000)));
